### ISSUE TITLE
get depth image

### ISSUE THREAD

**Issue by MasIgor** [ifm/o3d3xx-python#19]
Hello! 

first off thank you for the code.. 

i would need to get just a depth-map, to be able to extract the depth at a given pixel. Can this be done?

Thank you!

**Comment by MasIgor** [comment]
I managed to get the depth image, but fail to set the resolution to the camera's native resolution. the array i get from the camera is smaller than the destination array.

here is my code:

```

from __future__ import (absolute_import, division, print_function, unicode_literals)
from builtins import *
import o3d3xx
import sys
import time
import numpy as np
import cv2

#imageWidth = 176
#imageHeight = 132

imageWidth = 352
imageHeight = 264

class GrabO3D300():
    def __init__(self,data):
        self.data = data
        self.Distance = np.zeros((imageHeight,imageWidth))

    def readNextFrame(self):
        result = self.data.readNextFrame()
        self.Distance = np.frombuffer(result['distance_image'],dtype='uint16')
        self.Distance = self.Distance.reshape(imageHeight,imageWidth)
        self.illuTemp = 20.0




if len(sys.argv) > 1:
	address=sys.argv[1]
else:
	address='192.168.10.10'

camData = o3d3xx.FormatClient(address, 50010,
o3d3xx.PCICFormat.blobs("distance_image"))

grabber = GrabO3D300(camData)

imDistance = np.random.rand(imageHeight,imageWidth)

while True:
	result = camData.readNextFrame()
	frameCounter = frameCounter + 1
	grabber.readNextFrame()
	imDistance = grabber.Distance / 1000
	cv2.imshow('dist',imDistance)
	cv2.waitKey(1)

```


any help appreciated.. thank you

**Comment by graugans** [comment]
The default is a binning of the images, this is why you get the smaller resolution. If you activate the full resolution this may have an impact on the framerate. The resolution can be changed within the imager parameter **Resolution**:

Resolution of output image:  
- 0: 176 x 132 (2x2 binning)
- 1: 352 x 264 (no binning), only for 100k-camera

**Comment by graugans** [comment]
You can access the imager configuration like described [here](https://github.com/ifm/o3d3xx-python#rpc-client) under the topic `ImagerConfig object`

**Comment by MasIgor** [comment]
Thank you! got it.. :)
