### ISSUE TITLE
getting z-value instead of radial distance

### ISSUE THREAD

**Issue by MasIgor** [ifm/o3d3xx-python#21]
Hello!
Is there a way to get the Z value of any given point, instead of the radial distance?

if I take a measurement of a floor at 1 meter distance, I will read 1 meter in the center of the image, and increasingly larger values the more I get away from the center of the image, because the distance from any given point to the lense of the camera increases the more i go towards the edges of the taken picture. 

I would need to measure the same height all over the image.
Can this be done with this library?

Thank you

Best regards

Igor

**Comment by graugans** [comment]
The data you are looking for can be retrieved with [z_image](https://github.com/ifm/ifm3d/blob/main/modules/framegrabber/src/libifm3d_framegrabber/schema.cpp#L35)

The python code may look like this:

```python
pcic = o3d3xx.FormatClient(address, 50010,
	o3d3xx.PCICFormat.blobs("amplitude_image","z_image"))
	
 result = pcic.readNextFrame()
 # result['amplitude_image']
 # result['z_image']
```

**Comment by MasIgor** [comment]
thank you very much, worked like a charm! :)
