### ISSUE TITLE
Hanging on ImageClient()

### ISSUE THREAD

**Issue by jchevin** [ifm/o3d3xx-python#5]
Ive been doing dev work with PyCharm and this library to work with a o3x100 camera.

IFM Assistant is able to access the camera fine. 

Creating the Device object happens without dramas, but the minute I try to create an ImageClient object, python3 hangs until I opt to kill the process.

Have tried tracing it down, but unsure as of yet as to the origin (User error potentially)

**Comment by cfreundl** [comment]
The ImageClient has not been adapted yet to the O3X, and it is no surprise that it is not working as the data connections to O3D3xx devices are bidirectional whereas on O3X you cannot send commands to the camera, and that's where the client is hanging.

However, it is not hard to resolve: I have pushed a quick fix to the `o3x` branch (which I assume you are already using). The `ImageClient` class and along with it the examples `image_grabber.py` and `image_viewer.py` (requires the O3X application to output at least amplitude and distance image) should be working with an O3X.

**Comment by jchevin** [comment]
Thanks for the pointer Christoph, still feeling my way through the dev
environment for this camera!
