### ISSUE TITLE
cartesian coordinates from depth data

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [ifm/o3d3xx-python#9]
Hi, 

I am looking to get the cartesian coordinates from the depth data from camera, for the same I was looking at the example "libo3d3xx/modules/examples/ex-cartesian.cpp", I see that  Extrinsics values are added to the radial distances. In python I was looking at methord to get cameras Extrinsics  parameters but could not get one. Can you share how to get Extrinsic parameters using python lib, it will be good to get an example code.

SSH

**Comment by iadv** [comment]
What are the x,y,z values in the "result" variable? Aren't they what you are looking for?

**Comment by cfreundl** [comment]
Like @iadv already said, the cartesian coordinates should be present in the `x`, `y` and `z` entries of the result object returned by `o3d3xx.pcic.ImageClient.readNextFrame()`.
Concerning the extrinsic calibration, a colleague of mine is currently working on extending the library for that purpose and there should be a pull request soon.

**Comment by ShettyHarapanahalli** [comment]
Thanks for the information :)

**Comment by ShettyHarapanahalli** [comment]
Any update to this also can you please share an example to get cartesian coordinates in python.
